var alphabet = "abcdefghijklmnopqrstuvwxyz";

levelDictionaries = {
	canaria : {
		'lvl1' : 'crstneia',
		'lvl2' : 'dh',
		'lvl3' : 'lyuo',
		'lvl4' : 'pfgm',
		'lvl5' : 'bwkv',
		'lvl6' : 'jqzx',
		'lvl7' : alphabet,
	}
}



var layoutMaps = {
	canaria : {
		'Minus' : "-",
		'Equal' : "=",
		'KeyQ' : "w",
		'KeyW' : 'l',
		'KeyE' : 'y',
		'KeyR' : 'p',
		'KeyT' : 'b',
		'KeyY' : 'z',
		'KeyU' : 'f',
		'KeyI' : 'o',
		'KeyO' : 'u',
		'KeyP' : ';',
		'BracketLeft' : '[',
		'BracketRight' : ']',
		'Backslash' : '\\',
		'KeyA' : 'c',
		'KeyS' : 'r',
		'KeyD' : 's',
		'KeyF' : 't',
		'KeyG' : 'g',
		'KeyH' : 'm',
		'KeyJ' : 'n',
		'KeyK' : 'e',
		'KeyL' : 'i',
		'Semicolon' : 'a',
		'Quote' : "'",
		'KeyZ' : 'x',
		'KeyX' : 'v',
		'KeyC' : 'd',
		'KeyV' : 'k',
		'KeyB' : 'q',
		'KeyN' : 'j',
		'KeyM' : 'h',
		'Comma' : '/',
		'Period' : ',',
		'Slash' : '.',
		'shiftLayer' : 'default',
	},
	custom : {
		'Minus' : " ",
		'Equal' : " ",
		'KeyQ' : " ",
		'KeyW' : ' ',
		'KeyE' : ' ',
		'KeyR' : ' ',
		'KeyT' : ' ',
		'KeyY' : ' ',
		'KeyU' : ' ',
		'KeyI' : ' ',
		'KeyO' : ' ',
		'KeyP' : ' ',
		'BracketLeft' : ' ',
		'BracketRight' : ' ',
		'Backslash' : ' ',
		'KeyA' : ' ',
		'KeyS' : ' ',
		'KeyD' : ' ',
		'KeyF' : ' ',
		'KeyG' : ' ',
		'KeyH' : ' ',
		'KeyJ' : ' ',
		'KeyK' : ' ',
		'KeyL' : ' ',
		'Semicolon' : ' ',
		'Quote' : " ",
		'KeyZ' : ' ',
		'KeyX' : ' ',
		'KeyC' : ' ',
		'KeyV' : ' ',
		'KeyB' : ' ',
		'KeyN' : ' ',
		'KeyM' : ' ',
		'Comma' : ' ',
		'Period' : ' ',
		'Slash' : ' ',
		'shiftLayer' : 'default',
	},
}
